# Generated by Django 2.0.6 on 2018-06-26 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NormaPdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.IntegerField(default=0)),
                ('norma1', models.CharField(max_length=5)),
                ('norma2', models.CharField(max_length=5)),
                ('norma3', models.CharField(max_length=5)),
                ('conteudo', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TitulosNorma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_titulo', models.TextField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='normapdf',
            name='tituloFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='normas.TitulosNorma'),
        ),
    ]
